layout_spectrum: 0
color:
  saturation: 0
  lightness: 0.5438433
  brandStrength: 0.1291653
  brandColors:
    - '#000000'
    - '#FFFF5F'
    - '#585858'
    - '#818352'
    - '#D8DA5F'
  rhythmicContrast: 0.6501865
typography_spectrum: 0.6135336
name: IdeART Karamanlidis
